let tituloBienvenida;

export const traducciones = {
  'es': {
    //navbar
    'navbar.brand': 'Hostal San Jorge',
    'navbar.home': 'Home',
    'navbar.rooms': 'Habitaciones',
    'navbar.gallery': 'Galería',
    'navbar.howToArrive': 'Cómo Llegar',
    'navbar.faqs': 'Preguntas Frecuentes',
    'navbar.language': 'Idioma',
    //home
    // 'sectionWelcome.title': '`${tituloBienvenida}`',
    'sectionWelcome.description': 'Con más de 10 años brindando alojamiento a nuestros huéspedes, en Hostal San Jorge le ofrecemos un lugar cómodo, tranquilo e ideal para descansar. Descubra la serenidad y la hospitalidad en el corazón de Cafayate, provincia de Salta. Permítanos ser su hogar lejos de casa y disfrute de una experiencia agradable y memorable mientras explora los encantos de esta hermosa región argentina.',
    'sectionService.breakfastTitle': 'Servicio de Desayuno incluido',
    'sectionService.breakfastDescription': 'Comience sus mañanas con un rico desayuno para energizar su día. Te esperamos para brindarte nuestro servicio de desayuno, que podrás disfrutar cada mañana durante tu estadía en Hostal San Jorge.',
    'sectionOurRooms.title': 'Nuestras Habitaciones',
    'sectionOurRooms.description1': 'En Hostal San Jorge, entendemos que cada huésped es único. Por eso, ofrecemos habitaciones privadas diseñadas para su comodidad y tranquilidad, que van desde simples hasta quíntuples.',
    'sectionOurRooms.description2': '¡Tu espacio perfecto y la mejor experiencia la tendrás con nosotros!',
    'sectionOurRooms.btnSeeRooms': 'Ver Habitaciones',
    'sectionInfo.faqsTitle': 'Preguntas frecuentes',
    'sectionInfo.faqsDescription': 'Consultá las preguntas más frecuentes de nuestros huéspedes.',
    'sectionInfo.howToArriveTitle': 'Cómo llegar',
    'sectionInfo.howToArriveDescription': 'Hostal San Jorge se encuentra ubicado a 2 cuadras de la plaza principal de Cafayate.',
    'sectionInfo.galleryTitle': 'Galería',
    'sectionInfo.galleryDescription': 'También puedes ver más imágenes de nuestro Hostal.',
    //habitaciones
    'descriptionRooms.title':'Nuestras Habitaciones',
    'descriptionRooms.description':'Descubre el encanto y la comodidad de nuestras habitaciones. Cada espacio ha sido diseñado pensando en tu confort, ofreciendo una experiencia única en hospitalidad.',
    'descriptionRooms.description1':'¡Conoce nuestras habitaciones y no dudes en elegirnos.',
    'descriptionRooms.descriptionPayMethods':'También puedes ver:',
    'descriptionRooms.btnPayMethods':'Formas de pago',
    // 'cardRoom.title':`${tituloHabitacion}`,
    // 'cardRoom.descriptionBed':`${descripcionCama}`,
    // 'cardRoom.maximumCapacity':`${capacidadMaxima}`,
    // 'cardRoom.amenities1':`${wifi}`,
    // 'cardRoom.amenities2':`${ropaCama}`,
    // 'cardRoom.amenities3':`${ventilador}`,
    // 'cardRoom.amenities4':`${articulosTocador}`,
    // 'cardRoom.amenities5':`${banioPrivado}`,
    'cardRoom.btnMoreInfo':'Más información',
    //galeria
    'sectionGallery.title':'Galería de imágenes',
    'sectionGallery.description1':'¡Conoce nuestras instalaciones y habitaciones a través de nuestra galería de imágenes!',
    'sectionGallery.description2':'Puedes ver cada imagen en detalle',
    'sectionGallery.smallDescription':'Imágenes tomadas por Sol Herrera. Ig: solherrera.ar',
    //Como llegar
    'sectionHowToGet.title':'Cómo llegar a nuestro Hostal',
    'sectionHowToGet.description':'Encuéntranos con Google Maps',
    'sectionContact.title':'Visítanos',
    'sectionContact.address':'Calixto Mamaní 105, Cafayate, Provincia de Salta, Argentina',
    'sectionContact.telephone':'Teléfono',
    'sectionContact':'Déjanos tu mensaje',
    'formContact.name':'Nombre y Apellido:',
    'formContact.email':'Correo electrónico:',
    'formContact.message':'Mensaje:',
    'formContact.btnSubmit':'Enviar',
    //habitacion simple, doble, triple y quintuple
    'breadcrumb.home': 'Home',
    'breadcrumb.rooms': 'Habitaciones',
    'breadcrumb.simpleRoom': 'Habitación Simple',
    'roomDescription.title': 'Habitación Simple',
    'roomDescription.subtitle': 'Descripción',
    'roomDescription.description': 'Esta acogedora habitación cuenta con 1 cama individual y comodidades como Wi-Fi, baño privado, ropa de cama, toallas, artículos de tocador y ventilador de techo.',
    'roomDescription.wifi': 'Wi-Fi',
    'roomDescription.bedAndTowels': 'Ropa de cama y toallas',
    'roomDescription.toiletries': 'Artículos de tocador',
    'roomDescription.ceilingFan': 'Ventilador de techo',
    'roomDescription.privateBathroom': 'Baño privado',
    'roomDescription.checkIn': 'Check-In: 02:00 PM',
    'roomDescription.checkOut': 'Check-Out: 10:00 AM',
    'roomDescription.share':'Compartir',
    'contact.title': 'Por Consultas o Reservas:',
    'telephone': 'Teléfono',
    'fullscreen.close': 'Cerrar',
    'fullscreen.btnVolver': 'Volver',
    //preguntasFrecuentes
    'containerQuestions.title':'Preguntas Frecuentes',
    'containerQuestions.description':'Si tu pregunta no se encuentra aquí, no te preocupes. Puedes escribirnos o llamarnos y estaremos encantados en ayudarte a responder tus dudas.',
    'faq.question1': '¿A qué hora puedo realizar el Check-In (hora de ingreso)?',
    'faq.answer1': 'El Check-In está disponible a partir de las 02:00 pm.',
    'faq.question2': '¿A qué hora puedo realizar el Check-Out (hora de salida)?',
    'faq.answer2': 'El Ckeck-Out es hasta las 10:00 am.',
    'faq.question3': '¿El Desayuno está incluido en la Estadía?',
    'faq.answer3': '¡Sí, claro que sí! En nuestro hostal, ofrecemos servicio de desayuno cada mañana en el horario de las 08:15 a 09:45 am.',
    'faq.question4': '¿Cuáles son las Formas de pago?',
    'faq.question5': '¿El Hostal cuenta con Wi-Fi?',
    'faq.answer5': 'Sí, contamos con conexión Wi-Fi y puedes conectarte desde cualquier lugar del hostal, ya sea en tu habitación o en áreas comunes.',
    'faq.question6': '¿Las Habitaciones son Privadas o Compartidas?',
    'faq.answer6': ' En nuestro hostal, creemos que es fundamental garantizar la máxima comodidad y privacidad para nuestros huéspedes, por lo que todas las habitaciones fueron diseñadas como espacios privados, brindando un ambiente exclusivo para cada visitante.',
    'faq.question7': '¿Las Habitaciones cuentan con Aire Acondicionado?',
    'faq.answer7': 'Actualmente tenemos dos habitaciones dobles con aire acondicionado para brindarle una estancia aún más cómoda. Las demás habitaciones aún no disponen de este servicio.',
    'faq.question8': '¿Las Habitaciones cuentan con Televisión?',
    'faq.answer8': 'En nuestro hostal, nos enfocamos en brindar un espacio tranquilo e ideal para descansar, por lo que actualmente no ofrecemos servicio de televisión en ninguna de nuestras habitaciones o en áreas comunes. ¡Estamos aquí para que tu estancia sea lo más placentera posible!',
    'faq.question9': '¿Las Habitaciones cuentan con Baño privado?',
    'faq.answer9': 'Sí, todas nuestras habitaciones disponen de baño privado. Queremos asegurarnos de que tengas la mayor comodidad y privacidad durante tu estancia.',
    'faq.question10': '¿El Hostal cuenta con Estacionamiento?',
    'faq.answer10': 'En este momento, nuestro hostal no dispone de estacionamiento propio.',
    'faq.question11': '¿El Hostal cuenta con Piscina?',
    'faq.answer11': 'Nuestro hostal no cuenta con piscina.',
    'faq.question12': '¿Se aceptan mascotas?',
    'faq.answer12': 'No se aceptan mascotas por el momento.',
    'faq.question13': '¿Cómo puedo realizar una reserva?',
    'faq.answer13.description1.span1': 'Puedes realizar tu reserva de dos maneras: a través de WhatsApp o llamando a nuestro teléfono fijo. Para garantizar tu estadía, solicitamos un pago inicial del 50% como seña. Puedes realizar esta transacción a través de las',
    'faq.answer13.description1.link':'formas de pago',
    'faq.answer13.description1.span2':'habilitadas.',
    'faq.answer13.description2':'En caso de cancelación, te recomendamos notificarnos con al menos 12 horas de antelación para poder procesar el reintegro de la seña. Estas políticas nos permiten gestionar eficientemente nuestras reservas y brindarte el mejor servicio posible.',
    'faq.answer13.description3':' En caso de llegar más tarde de lo previsto, por favor comunícate con nosotros para informarnos. Esto nos ayuda a asegurarnos de tu llegada. Apreciamos tu colaboración, especialmente en períodos de alta demanda.',
    'faq.answer13.description4':'Si tienes alguna pregunta adicional, estamos disponibles para ayudarte.',
    //seccion formas de pago, modal formas de pago y respuesta formas de pago
    'paymentMethods.title': 'Formas de Pago',
    'paymentMethods.payment1': 'Pago en efectivo.',
    'paymentMethods.payment2': 'Transferencias bancarias.',
    'paymentMethods.payment3': 'Link de la app MercadoPago para que puedas pagar con tu tarjeta de débito o crédito. (Esta operación tiene un 10% de recargo)',
    //amenities
    'amenities.title': 'Comodidades',
    'amenities.wifi': 'Wi-Fi',
    'amenities.bedAndTowels': 'Ropa de cama y toallas',
    'amenities.ceilingFan': 'Ventilador de techo',
    'amenities.AirAconditionerAndCeilingFan': 'Aire acondicionado y ventilador de techo',
    'amenities.privateBathroom': 'Baño privado',
    //footer
    'footer.info': 'Información',
    'footer.socialMedia': 'Síguenos en nuestras redes'
  },
  'en': {
    //navbar
    'navbar.brand': 'Hostal San Jorge',
    'navbar.home': 'Home',
    'navbar.rooms': 'Rooms',
    'navbar.gallery': 'Gallery',
    'navbar.howToArrive': 'How to Arrive',
    'navbar.faqs': 'Faqs',
    'navbar.language': 'Language',
    //home
    // 'sectionWelcome.title': `${tituloBienvenida}`,
    'sectionWelcome.description': '',
    'sectionService.breakfastTitle': '',
    'sectionService.breakfastDescription': '',
    'sectionOurRooms.title': 'Our Rooms',
    'sectionOurRooms.description1': '',
    'sectionOurRooms.description2': '¡',
    'sectionOurRooms.btnSeeRooms': '',
    'sectionInfo.faqsTitle': '',
    'sectionInfo.faqsDescription': '',
    'sectionInfo.howToArriveTitle': '',
    'sectionInfo.howToArriveDescription': '',
    'sectionInfo.galleryTitle': 'Gallery',
    'sectionInfo.galleryDescription': '',
    //habitaciones
    'descriptionRooms.title':'Our Rooms',
    'descriptionRooms.description':'',
    'descriptionRooms.description1':'',
    'descriptionRooms.descriptionPayMethods':'',
    'descriptionRooms.btnPayMethods':'',
    // 'cardRoom.title':`${tituloHabitacion}`,
    // 'cardRoom.descriptionBed':`${descripcionCama}`,
    // 'cardRoom.maximumCapacity':`${capacidadMaxima}`,
    // 'cardRoom.amenities1':`${wifi}`,
    // 'cardRoom.amenities2':`${ropaCama}`,
    // 'cardRoom.amenities3':`${ventilador}`,
    // 'cardRoom.amenities4':`${articulosTocador}`,
    // 'cardRoom.amenities5':`${banioPrivado}`,
    'cardRoom.btnMoreInfo':'Más información',
    //galeria
    'sectionGallery.title':'',
    'sectionGallery.description1':'',
    'sectionGallery.description2':'',
    'sectionGallery.smallDescription':'',
    //Como llegar
    'sectionHowToGet.title':'',
    'sectionHowToGet.description':'',
    'sectionContact.title':'',
    'sectionContact.address':'',
    'sectionContact.telephone':'Telephone',
    'sectionContact':'',
    'formContact.name':'',
    'formContact.email':'E-mail:',
    'formContact.message':'Message:',
    'formContact.btnSubmit':'Submit',
    //habitacion simple, doble, triple y quintuple
    'breadcrumb.home': 'Home',
    'breadcrumb.rooms': 'Rooms',
    'breadcrumb.simpleRoom': '',
    'roomDescription.title': '',
    'roomDescription.subtitle': 'Description',
    'roomDescription.description': '',
    'roomDescription.wifi': 'Wi-Fi',
    'roomDescription.bedAndTowels': '',
    'roomDescription.toiletries': '',
    'roomDescription.ceilingFan': '',
    'roomDescription.privateBathroom': '',
    'roomDescription.share':'Share',
    'contact.title': '',
    'telephone': 'Telephone',
    'fullscreen.close': 'Close',
    'fullscreen.btnVolver': 'Back',
    //preguntasFrecuentes
    'containerQuestions.title':'',
    'containerQuestions.description':'',
    'faq.question1': '¿ Check-In?',
    'faq.answer1': '',
    'faq.question2': '¿ Check-Out ?',
    'faq.answer2': '',
    'faq.question3': '¿?',
    'faq.answer3': '',
    'faq.question5': '¿?',
    'faq.answer5': '',
    'faq.question6': '',
    'faq.answer6': '',
    'faq.question7': '¿?',
    'faq.answer7': '',
    'faq.question8': '¿?',
    'faq.answer8': '',
    'faq.question9': '¿?',
    'faq.answer9': '',
    'faq.question10': '¿?',
    'faq.answer10': '',
    'faq.question11': '¿?',
    'faq.answer11': '',
    'faq.question12': '¿?',
    'faq.answer12': '',
    'faq.question13': '¿?',
    'faq.answer13.description1.span1': '',
    'faq.answer13.description1.link':'',
    'faq.answer13.description1.span2':'',
    'faq.answer13.description2':'',
    'faq.answer13.description3':'',
    'faq.answer13.description4':'',
    //seccion formas de pago, modal formas de pago y respuesta formas de pago
    'paymentMethods.title': '',
    'paymentMethods.payment1': '',
    'paymentMethods.payment2': '',
    'paymentMethods.payment3': '',
    //amenities
    'amenities.title': 'Amenities',
    'amenities.wifi': '',
    'amenities.bedAndTowels': '',
    'amenities.ceilingFan': '',
    'amenities.AirAconditionerAndCeilingFan': '',
    'amenities.privateBathroom': '',
    //footer
    'footer.info': 'Information',
    'footer.socialMedia': ''
  },
}