export const traducciones = {
  'es': {
    'rooms': 'Habitaciones',
    'gallery': 'Galería',
    'howToGet': 'Cómo Llegar',
    'faqs': 'Preguntas Frecuentes',
    'language': 'Idioma',
    'sectionWelcome.title': 'Bienvenido a',
    'sectionWelcome.description': 'Con más de 10 años brindando alojamiento a nuestros huéspedes, en Hostal San Jorge le ofrecemos un lugar cómodo, tranquilo e ideal para descansar. Descubra la serenidad y la hospitalidad en el corazón de Cafayate, provincia de Salta. Permítanos ser su hogar lejos de casa y disfrute de una experiencia agradable y memorable mientras explora los encantos de esta hermosa región argentina.',
    'sectionService.breakfastTitle': 'Servicio de Desayuno incluido',
    'sectionService.breakfastDescription': 'Comience sus mañanas con un rico desayuno para energizar su día. Te esperamos para brindarte nuestro servicio de desayuno, que podrás disfrutar durante tu estadía.',
    'sectionOurRooms.title': 'Nuestras Habitaciones',
    'sectionOurRooms.description1': 'En Hostal San Jorge, entendemos que cada huésped es único. Por eso, ofrecemos habitaciones privadas diseñadas para su comodidad y tranquilidad, que van desde simples hasta quíntuples.',
    'sectionOurRooms.description2': '¡Tu espacio perfecto y la mejor experiencia la tendrás con nosotros!',
    'sectionOurRooms.btnSeeRooms': 'Ver Habitaciones',
    'sectionInfo.faqsTitle': 'Preguntas frecuentes',
    'sectionInfo.faqsDescription': 'Consultá las preguntas más frecuentes de nuestros huéspedes.',
    'sectionInfo.howToArriveTitle': 'Cómo llegar',
    'sectionInfo.howToArriveDescription': 'Hostal San Jorge se encuentra ubicado a 2 cuadras de la plaza principal de Cafayate.',
    'sectionInfo.galleryTitle': 'Galería',
    'sectionInfo.galleryDescription': 'También puedes ver más imágenes de nuestro Hostal.',
    'sectionInfo.SeeMore':'Ver más',
    'descriptionRooms.title':'Nuestras Habitaciones',
    'descriptionRooms.description':'Descubre el encanto y la comodidad de nuestras habitaciones. Cada espacio ha sido diseñado pensando en tu confort, ofreciendo una experiencia única en hospitalidad.',
    'descriptionRooms.description1':'¡Conoce nuestras habitaciones y no dudes en elegirnos!',
    'descriptionRooms.descriptionPayMethods':'También puedes ver:',
    'descriptionRooms.btnPayMethods':'Formas de pago',
    'cardRoom.descriptionBedSingle':'1 cama individual.',
    'cardRoom.descriptionBedDouble':'1 cama matrimonial.',
    'cardRoom.descriptionBedTriple':'1 cama matrimonial y 1 cama individual.',
    'cardRoom.descriptionBedQuintuple':'1 cama matrimonial, 1 cama individual y 1 cama cucheta.',
    'cardRoom.maximumCapacitySingle':'Capacidad Máxima:',
    'cardRoom.maximumCapacityDouble':'Capacidad Máxima:',
    'cardRoom.maximumCapacityTriple':'Capacidad Máxima:',
    'cardRoom.maximumCapacityQuintuple':'Capacidad Máxima:',
    'cardRoom.btnMoreInfo':'Más información',
    'btnCheckRoom': 'Consultar Habitación',
    'sectionGallery.title':'Galería de imágenes',
    'sectionGallery.description1':'¡Conoce nuestras instalaciones y habitaciones a través de nuestra galería de imágenes!',
    'sectionGallery.description2':'Puedes ver cada imagen en detalle.',
    'sectionGallery.description3':'Imágenes tomadas por Sol Herrera. Ig: solherrera.ar',
    'sectionHowToGet.title':'Cómo llegar a nuestro Hostal',
    'sectionHowToGet.description':'Encuéntranos con Google Maps',
    'sectionContact.title':'Visítanos',
    'sectionContact.address':'Calixto Mamaní 105, Cafayate, Provincia de Salta, Argentina',
    'sectionContact.telephone':'Teléfono',
    'sectionContact':'Deja tu mensaje',
    'formContact.name':'Nombre y Apellido:',
    'formContact.email':'Correo electrónico:',
    'formContact.message':'Mensaje:',
    'formContact.btnSubmit':'Enviar',
    'simpleRoom': 'Habitación Individual',
    'dobleRoom': 'Habitación Doble',
    'tripleRoom': 'Habitación Triple',
    'quintupleRoom': 'Habitación Quíntuple',
    'roomDescription.subtitle': 'Descripción',
    'roomDescription.descriptionSingle': 'Esta acogedora habitación cuenta con 1 cama individual para una sola persona y comodidades como Wi-Fi, baño privado, ropa de cama, toallas, artículos de tocador y ventilador de techo.',
    'roomDescription.descriptionDouble':'Esta habitación cuenta con 1 cama matrimonial para 2 personas y comodidades como Wi-Fi, aire acondicionado, baño privado, ropa de cama, toallas, artículos de tocador y ventilador de techo. Además cuenta con un mini balcón.',
    'roomDescription.descriptionTriple':'Esta habitación para 3 personas cuenta con 1 cama matrimonial y 1 cama individual. Incluye comodidades como Wi-Fi, baño privado, ropa de cama, toallas, artículos de tocador y ventilador de techo.',
    'roomDescription.descriptionQuintuple':'Esta amplia y cómoda habitación para 5 personas cuenta con 1 cama matrimonial, 1 cama individual y 1 cama cucheta. Incluye comodidades como Wi-Fi, baño privado, ropa de cama, toallas, artículos de tocador y ventilador de techo.',
    'roomDescription.share':'Compartir:',
    'contact.title': 'Por Consultas o Reservas:',
    'telephone': 'Teléfono',
    'fullscreen.btnClose': 'Cerrar',
    'fullscreen.btnVolver': 'Volver',
    'containerQuestions.title':'Preguntas Frecuentes',
    'containerQuestions.description':'Si tu pregunta no se encuentra aquí, no te preocupes. Puedes escribirnos o llamarnos y estaremos encantados en ayudarte a responder tus dudas.',
    'faq.question1': '¿A qué hora puedo realizar el Check-In (hora de ingreso)?',
    'faq.answer1': 'El Check-In está disponible a partir de las 02:00 pm.',
    'faq.question2': '¿A qué hora puedo realizar el Check-Out (hora de salida)?',
    'faq.answer2': 'El Ckeck-Out es hasta las 10:00 am.',
    'faq.question3': '¿El Desayuno está incluido en la Estadía?',
    'faq.answer3': '¡Sí, claro que sí! En nuestro hostal, ofrecemos servicio de desayuno cada mañana en el horario de las 08:15 a 09:45 am.',
    'faq.question4': '¿Cuáles son las Formas de pago?',
    'faq.question5': '¿El Hostal cuenta con Wi-Fi?',
    'faq.answer5': 'Sí, contamos con conexión Wi-Fi y puedes conectarte desde cualquier lugar del hostal, ya sea en tu habitación o en áreas comunes.',
    'faq.question6': '¿Las Habitaciones son Privadas o Compartidas?',
    'faq.answer6': 'En nuestro hostal, creemos que es fundamental garantizar la máxima comodidad y privacidad para nuestros huéspedes, por lo que todas las habitaciones fueron diseñadas como espacios privados, brindando un ambiente exclusivo para cada visitante.',
    'faq.question7': '¿Las Habitaciones cuentan con Aire Acondicionado?',
    'faq.answer7': 'Actualmente tenemos dos habitaciones dobles con aire acondicionado para brindarle una estancia aún más cómoda. Las demás habitaciones aún no disponen de este servicio.',
    'faq.question8': '¿Las Habitaciones cuentan con Televisión?',
    'faq.answer8': 'En nuestro hostal, nos enfocamos en brindar un espacio tranquilo e ideal para descansar, por lo que actualmente no ofrecemos servicio de televisión en ninguna de nuestras habitaciones o en áreas comunes. ¡Estamos aquí para que tu estancia sea lo más placentera posible!',
    'faq.question9': '¿Las Habitaciones cuentan con Baño privado?',
    'faq.answer9': 'Sí, todas nuestras habitaciones disponen de baño privado. Queremos asegurarnos de que tengas la mayor comodidad y privacidad durante tu estancia.',
    'faq.question10': '¿El Hostal cuenta con Estacionamiento?',
    'faq.answer10': 'En este momento, nuestro hostal no dispone de estacionamiento propio.',
    'faq.question11': '¿El Hostal cuenta con Piscina?',
    'faq.answer11': 'Nuestro hostal no cuenta con piscina.',
    'faq.question12': '¿Se aceptan mascotas?',
    'faq.answer12': 'No se aceptan mascotas por el momento.',
    'faq.question13': '¿Cómo puedo realizar una reserva?',
    'faq.answer13.description1.span1': 'Puedes realizar tu reserva de dos maneras: a través de WhatsApp o llamando a nuestro teléfono fijo. Para garantizar tu estadía, solicitamos un pago inicial del 50% como seña. Puedes realizar esta transacción a través de las',
    'faq.answer13.description1.link':'formas de pago',
    'faq.answer13.description1.span2':'habilitadas.',
    'faq.answer13.description2':'En caso de cancelación, te recomendamos notificarnos con al menos 12 horas de antelación para poder procesar el reintegro de la seña. Estas políticas nos permiten gestionar eficientemente nuestras reservas y brindarte el mejor servicio posible.',
    'faq.answer13.description3':' En caso de llegar más tarde de lo previsto, por favor comunícate con nosotros para informarnos. Esto nos ayuda a asegurarnos de tu llegada. Apreciamos tu colaboración, especialmente en períodos de alta demanda.',
    'faq.answer13.description4':'Si tienes alguna pregunta adicional, estamos disponibles para ayudarte.',
    'paymentMethods.title': 'Formas de Pago',
    'paymentMethods.payment1': 'Pago en efectivo.',
    'paymentMethods.payment2': 'Transferencias bancarias.',
    'paymentMethods.payment3': 'Link de la app MercadoPago para que puedas pagar con tu tarjeta de débito o crédito. (Esta operación tiene un 10% de recargo)',  
    'amenities.title': 'Comodidades',
    'amenities.subtitle': 'Comodidades:',
    'amenities.wifi': 'Wi-Fi',
    'amenities.bedAndTowels': 'Ropa de cama y toallas',
    'amenities.ceilingFan': 'Ventilador de techo',
    'amenities.AirAconditionerAndCeilingFan': 'Aire acondicionado y ventilador de techo',
    'amenities.AirAconditioner': 'Aire acondicionado',
    'amenities.privateBathroom': 'Baño privado',
    'amenities.toiletries':'Artículos de tocador',
    'language.es':'Español',
    'language.en':'Inglés',
    'footer.info': 'Información',
    'footer.telephone': 'Teléfono: +54 9 03868 422388',
    'footer.socialMedia': 'Síguenos en nuestras redes',
    'footer.rightsReserved': '©Todos los derechos reservados. 2024.',
    'footer.designedBy': 'Diseñado por',
    'footer.name': 'Bruno Madozzo'
  },
  'en': {
    'rooms': 'Rooms',
    'gallery': 'Gallery',
    'howToGet': 'How to get',
    'faqs': 'Faqs',
    'language': 'Language',
    'sectionWelcome.title': 'Welcome to',
    'sectionWelcome.description': 'With more than 10 years providing accommodation to our guests, at Hostal San Jorge we offer a comfortable, quiet and ideal place to rest. Discover serenity and hospitality in the centre of Cafayate, Salta province. Let us be your home away from home and enjoy an enjoyable and memorable experience while exploring the charms of this beautiful Argentine region.',
    'sectionService.breakfastTitle': 'Breakfast service included',
    'sectionService.breakfastDescription': 'Start your mornings with a delicious breakfast to energize your day. We are waiting for you to provide you with our breakfast service, which you can enjoy during your stay.',
    'sectionOurRooms.title': 'Our Rooms',
    'sectionOurRooms.description1': 'At Hostal San Jorge, we understand that each guest is unique. For this reason, we offer private rooms designed for your comfort and tranquility, ranging from single to quintuple.',
    'sectionOurRooms.description2': '¡Your perfect place and the best experience you will have with us!',
    'sectionOurRooms.btnSeeRooms': 'See Rooms',
    'sectionInfo.faqsDescription': 'Check out the most frequent questions from our guests.',
    'sectionInfo.howToArriveDescription': 'Hostal San Jorge is located 2 blocks from the main square of Cafayate.',
    'sectionInfo.galleryDescription': 'You can also see more images of our Hostel.',
    'sectionInfo.SeeMore':'See more',
    'descriptionRooms.title':'Our Rooms',
    'descriptionRooms.description':'Discover the charm and comfort of our rooms. Each space has been designed thinking about your comfort, offering a unique hospitality experience.',
    'descriptionRooms.description1':'¡Get to know our rooms and do not hesitate to choose us!',
    'descriptionRooms.descriptionPayMethods':'You can also see:',
    'descriptionRooms.btnPayMethods':'Payment Methods',
    'cardRoom.descriptionBedSingle':'1 single bed.',
    'cardRoom.descriptionBedDouble':'1 double bed',
    'cardRoom.descriptionBedTriple':'1 double bed and 1 single bed',
    'cardRoom.descriptionBedQuintuple':'1 double bed, 1 single bed and 1 bunk bed.',
    'cardRoom.maximumCapacitySingle':'Maximum capacity:',
    'cardRoom.maximumCapacityDouble':'Maximum capacity:',
    'cardRoom.maximumCapacityTriple':'Maximum capacity:',
    'cardRoom.maximumCapacityQuintuple':'Maximum capacity:',
    'cardRoom.btnMoreInfo':'More information',
    'btnCheckRoom': 'Check Room',
    'sectionGallery.title':'Image Gallery',
    'sectionGallery.description1':'¡Get to know our facilities and rooms through our image gallery!',
    'sectionGallery.description2':'You can see each image in detail.',
    'sectionGallery.description3': 'Photographed by Sol Herrera. Ig: solherrera.ar',
    'sectionHowToGet.title':'How to get to our Hostel',
    'sectionHowToGet.description':'Find us with Google Maps',
    'sectionContact.title':'Visit us',
    'sectionContact.address':'Calixto Mamaní 105, Cafayate, Salta Province, Argentina',
    'sectionContact':'Leave your message',
    'formContact.name':'Name and Surname:',
    'formContact.email':'Email:',
    'formContact.message':'Message:',
    'formContact.btnSubmit':'Submit',
    'simpleRoom': 'Single Room',
    'dobleRoom': 'Double Room',
    'tripleRoom': 'Triple Room',
    'quintupleRoom': 'Quintuple Room',
    'roomDescription.subtitle': 'Description',
    'roomDescription.descriptionSingle': 'This cozy room features a single bed for a single person and amenities such as Wi-Fi, private bathroom, linens, towels, toiletries and ceiling fan.',
    'roomDescription.descriptionDouble':'This room has 1 double bed (2 people) and amenities such as Wi-Fi, air conditioning, private bathroom, bed linen, towels, toiletries and ceiling fan. It also has a mini balcony.',
    'roomDescription.descriptionTriple':'Three people room with one double bed and a single bed. Includes wi-fi , private bathroom , linens and towells , basic toiletries and ceiling fan.',
    'roomDescription.descriptionQuintuple':'This spacious and comfortable room for 5 people has 1 double bed, 1 single bed and 1 bunk bed. Includes amenities such as Wi-Fi, private bathroom, linens, towels, toiletries and ceiling fan.',
    'roomDescription.share':'Share:',
    'contact.title': 'For Questions or Reservations:',
    'telephone': 'Telephone',
    'fullscreen.btnClose': 'Close',
    'fullscreen.btnVolver': 'Return',
    'containerQuestions.title':'Faqs',
    'containerQuestions.description':"If your question isn't here, don't worry. You can text or call us and we'll be glad to help you solving your doubts.",
    'faq.question1': '¿Time to check-in (entering hour)?',
    'faq.answer1': 'Check-in available since 02:00 p.m.',
    'faq.question2': '¿Time to check-out (leaving hour)?',
    'faq.answer2': 'Check-out is available till 10:00 a.m.',
    'faq.question3': '¿Is breakfast included with the stay ?',
    'faq.answer3': '¡Yes, of course! Our place offer breakfast service every morning between 08:15 and 09:45.',
    'faq.question4': '¿Payment methods?',
    'faq.question5': '¿Does the Hostel have Wi-Fi?',
    'faq.answer5': 'We have Wi-Fi connection and you can connect from anywhere in the hostel, whether in your room or in common areas.',
    'faq.question6': '¿Private or shared rooms?',
    'faq.answer6': 'We believe in the fact that is fundamental make sure comfort and privacy to our residents, because of that all rooms were designed to be private spaces, offering exclusive place to every guest.',
    'faq.question7': '¿Do the rooms have air conditioning?',
    'faq.answer7': 'We currently have two air-conditioned double rooms to provide you with an even more comfortable stay. The other rooms do not yet have this service.',
    'faq.question8': '¿Do the rooms have television?',
    'faq.answer8': 'At our hostel, we focus on providing a quiet and ideal space to rest, that is why we currently do not offer television service in any of our rooms or in common areas. ¡We effort in make your stay as pleasant as possible!',
    'faq.question9': '¿Do the rooms have private bathroom?',
    'faq.answer9': 'Yes, all our rooms have private bathroom. We want to ensure that you have the greatest comfort and privacy during your stay.',
    'faq.question10': '¿Does the Hostel have Parking?',
    'faq.answer10': 'At this time, our hostel does not have its own parking.',
    'faq.question11': '¿Does the Hostel have a swimming pool?',
    'faq.answer11': 'Our hostel does not have a swimming pool.',
    'faq.question12': '¿Are pets allowed?',
    'faq.answer12': 'Pets are not accepted at the moment.',
    'faq.question13': '¿How can I make a reservation?',
    'faq.answer13.description1.span1': 'In order to guarantee your stay, we solicitate an initial payment of 50% as warranty. You can realize this transaction through the accepted',
    'faq.answer13.description1.link':'ways of payment.',
    'faq.answer13.description1.span2':'',
    'faq.answer13.description2':'In cancelattion case, we recomend notifying us, at least twelve hours before, to process the devolution of your warranty money. This policy allows us an efficient management of our reservations and allows us to provide you with the best possible service.',
    'faq.answer13.description3':'In case of late arriving, please communicate us to be in knowledge of the Situation. It permit us be sure of your arriving. Your colaboration is well appreciate, especially in high season.',
    'faq.answer13.description4':'For adittional questions, we are always able to solve your doubts.',
    'paymentMethods.title': 'Payment Methods',
    'paymentMethods.payment1': 'Cash payment.',
    'paymentMethods.payment2': 'Bank transfer.',
    'paymentMethods.payment3': 'Payment link (mercado pago) we receive all debit card, and credit card (10% adittional)',
    'amenities.title': 'Amenities',
    'amenities.subtitle': 'Amenities:',
    'amenities.wifi': 'Wi-Fi',
    'amenities.bedAndTowels': 'Linens and towels',
    'amenities.ceilingFan': 'Ceiling fan',
    'amenities.AirAconditionerAndCeilingFan': 'Air conditioner and ceiling fan',
    'amenities.AirAconditioner': 'Air conditioner',
    'amenities.privateBathroom': 'Private bathroom',
    'amenities.toiletries':'Toiletries',
     'language.es':'Spanish',
     'language.en':'English',
    'footer.info': 'Information',
    'footer.telephone': 'Telephone: +54 9 03868 422388',
    'footer.socialMedia': 'Follow us on our networks',
    'footer.rightsReserved': '©All rights reserved. 2024.',
    'footer.designedBy': 'Designed by',
    'footer.name': ' Bruno Madozzo'
  },
}