export const paises = [
    { code: "AR", name: "Argentina", phone: "+54" },
    { code: "BR", name: "Brasil", phone: "+55" },
    { code: "CL", name: "Chile", phone: "+56" },
    { code: "UY", name: "Uruguay", phone: "+598" },
    { code: "PY", name: "Paraguay", phone: "+595" },
    { code: "US", name: "Estados Unidos", phone: "+1" },
    { code: "MX", name: "México", phone: "+52" },
    { code: "ES", name: "España", phone: "+34" },
    { code: "IT", name: "Italia", phone: "+39" },
    { code: "DE", name: "Alemania", phone: "+49" },
    { code: "FR", name: "Francia", phone: "+33" },
    { code: "UK", name: "Reino Unido", phone: "+44" },
    { code: "AU", name: "Australia", phone: "+61" },
    { code: "NZ", name: "Nueva Zelanda", phone: "+64" },
    { code: "JP", name: "Japón", phone: "+81" },
    { code: "CN", name: "China", phone: "+86" },
    { code: "RU", name: "Rusia", phone: "+7" },
    { code: "CA", name: "Canadá", phone: "+1" },
    { code: "CO", name: "Colombia", phone: "+57" },
    { code: "PE", name: "Perú", phone: "+51" },
    { code: "EC", name: "Ecuador", phone: "+593" },
    { code: "VE", name: "Venezuela", phone: "+58" },
    { code: "BO", name: "Bolivia", phone: "+591" },
    { code: "PT", name: "Portugal", phone: "+351" },
  ];
  